// DDL 生成器冒烟测试：node scripts/test-ddl.mjs（先用 esbuild 打包 ddl.ts）
import { execSync } from 'child_process'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { createRequire } from 'module'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
execSync(
  `npx esbuild src/renderer/src/ddl.ts --bundle --platform=node --format=cjs ` +
    `--alias:@shared=./src/shared --alias:@=./src/renderer/src --outfile=scripts/.ddl-bundle.cjs`,
  { cwd: root, stdio: 'inherit' }
)

const require = createRequire(import.meta.url)
const ddl = require(join(root, 'scripts/.ddl-bundle.cjs'))

let failures = 0
function check(label, actual, ...substrings) {
  const text = Array.isArray(actual) ? actual.join(';\n') : String(actual)
  for (const s of substrings) {
    if (!text.includes(s)) {
      failures++
      console.error(`✗ ${label}\n  缺少: ${s}\n  实际: ${text}\n`)
      return
    }
  }
  console.log(`✓ ${label}`)
}

const col = (p) => ({
  key: p.name, name: '', type: '', length: '', scale: '',
  notNull: false, pk: false, autoIncrement: false, defaultValue: '', comment: '', ...p
})

// ---- CREATE TABLE: MySQL ----
const mysqlDesign = {
  name: 'users',
  columns: [
    col({ name: 'id', type: 'int', pk: true, notNull: true, autoIncrement: true }),
    col({ name: 'name', type: 'varchar', length: '64', notNull: true, comment: '姓名' }),
    col({ name: 'balance', type: 'decimal', length: '10', scale: '2', defaultValue: '0' }),
    col({ name: 'created_at', type: 'datetime', defaultValue: 'CURRENT_TIMESTAMP' })
  ],
  indexes: [{ key: 'i1', name: 'idx_name', columns: ['name'], unique: true, method: 'BTREE' }],
  foreignKeys: [],
  comment: '用户表',
  engine: 'InnoDB',
  charset: 'utf8mb4'
}
check('MySQL CREATE', ddl.generateCreateTable('mysql', 'mydb', mysqlDesign),
  'CREATE TABLE `mydb`.`users`',
  '`id` int NOT NULL AUTO_INCREMENT',
  "`name` varchar(64) NOT NULL COMMENT '姓名'",
  '`balance` decimal(10,2) DEFAULT 0',
  'DEFAULT CURRENT_TIMESTAMP',
  'PRIMARY KEY (`id`)',
  'UNIQUE INDEX `idx_name` (`name`) USING BTREE',
  "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表'")

// ---- CREATE TABLE: PostgreSQL ----
const pgDesign = {
  name: 'orders',
  columns: [
    col({ name: 'id', type: 'bigint', pk: true, notNull: true, autoIncrement: true }),
    col({ name: 'user_id', type: 'integer', notNull: true, comment: '用户ID' }),
    col({ name: 'status', type: 'character varying', length: '20', defaultValue: 'new' })
  ],
  indexes: [{ key: 'i1', name: 'idx_orders_user', columns: ['user_id'], unique: false, method: 'btree' }],
  foreignKeys: [{
    key: 'f1', name: 'fk_orders_user', columns: ['user_id'],
    refTable: 'users', refColumns: ['id'], onUpdate: 'NO ACTION', onDelete: 'CASCADE'
  }],
  comment: '订单'
}
check('PG CREATE', ddl.generateCreateTable('postgresql', 'mydb', pgDesign),
  'CREATE TABLE "public"."orders"',
  '"id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY',
  `"status" character varying(20) DEFAULT 'new'`,
  'PRIMARY KEY ("id")',
  'CONSTRAINT "fk_orders_user" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE CASCADE',
  'CREATE INDEX "idx_orders_user" ON "public"."orders" USING btree ("user_id")',
  `COMMENT ON TABLE "public"."orders" IS '订单'`,
  `COMMENT ON COLUMN "public"."orders"."user_id" IS '用户ID'`)

// ---- CREATE TABLE: SQLite 整数主键内联 ----
const sqliteDesign = {
  name: 'logs',
  columns: [
    col({ name: 'id', type: 'INTEGER', pk: true, autoIncrement: true }),
    col({ name: 'msg', type: 'TEXT', notNull: true })
  ],
  indexes: [], foreignKeys: [], comment: ''
}
check('SQLite CREATE 内联主键', ddl.generateCreateTable('sqlite', 'main', sqliteDesign),
  '"id" INTEGER PRIMARY KEY AUTOINCREMENT',
  '"msg" TEXT NOT NULL')

// ---- ALTER: MySQL 改列/加列/删列/重命名 ----
const origDesign = {
  name: 'users',
  columns: [
    col({ name: 'id', originalName: 'id', type: 'int', pk: true, notNull: true, autoIncrement: true }),
    col({ name: 'name', originalName: 'name', type: 'varchar', length: '64', notNull: true }),
    col({ name: 'old_col', originalName: 'old_col', type: 'int' })
  ],
  indexes: [{ key: 'i1', originalName: 'idx_a', name: 'idx_a', columns: ['name'], unique: false }],
  foreignKeys: [], comment: '', engine: 'InnoDB'
}
const newDesign = {
  name: 'users',
  columns: [
    col({ name: 'id', originalName: 'id', type: 'int', pk: true, notNull: true, autoIncrement: true }),
    col({ name: 'full_name', originalName: 'name', type: 'varchar', length: '128', notNull: true }),
    col({ name: 'email', type: 'varchar', length: '255' })
  ],
  indexes: [],
  foreignKeys: [], comment: '', engine: 'InnoDB'
}
check('MySQL ALTER', ddl.generateAlterTable('mysql', 'mydb', { name: 'users', design: origDesign }, newDesign),
  'DROP INDEX `idx_a`',
  'DROP COLUMN `old_col`',
  'CHANGE `name` `full_name` varchar(128) NOT NULL',
  'ADD COLUMN `email` varchar(255)')

// ---- ALTER: PG 类型/默认值/重命名 ----
const pgOrig = {
  name: 'orders',
  columns: [
    col({ name: 'status', originalName: 'status', type: 'character varying', length: '20' })
  ],
  indexes: [], foreignKeys: [], comment: ''
}
const pgNew = {
  name: 'orders',
  columns: [
    col({ name: 'state', originalName: 'status', type: 'character varying', length: '40', notNull: true, defaultValue: 'new' })
  ],
  indexes: [], foreignKeys: [], comment: ''
}
check('PG ALTER', ddl.generateAlterTable('postgresql', 'mydb', { name: 'orders', design: pgOrig, pkConstraint: 'orders_pkey' }, pgNew),
  'ALTER COLUMN "status" TYPE character varying(40)',
  'ALTER COLUMN "status" SET NOT NULL',
  `ALTER COLUMN "status" SET DEFAULT 'new'`,
  'RENAME COLUMN "status" TO "state"')

// ---- ALTER: SQLite 不支持的变更要有警告 ----
const sqliteOrig = {
  name: 'logs',
  columns: [col({ name: 'msg', originalName: 'msg', type: 'TEXT' })],
  indexes: [], foreignKeys: [], comment: ''
}
const sqliteNew = {
  name: 'logs',
  columns: [col({ name: 'msg', originalName: 'msg', type: 'INTEGER' })],
  indexes: [], foreignKeys: [], comment: ''
}
check('SQLite ALTER 警告', ddl.generateAlterTable('sqlite', 'main', { name: 'logs', design: sqliteOrig }, sqliteNew),
  '-- 警告: SQLite 不支持修改列定义')

// ---- 结构同步：对齐 + diff ----
// 源：id, name(varchar 128), email；目标：id, name(varchar 64), legacy_col
const syncSrc = {
  name: 'users',
  columns: [
    col({ name: 'id', originalName: 'id', type: 'int', pk: true, notNull: true }),
    col({ name: 'name', originalName: 'name', type: 'varchar', length: '128', notNull: true }),
    col({ name: 'email', originalName: 'email', type: 'varchar', length: '255' })
  ],
  indexes: [{ key: 'i1', originalName: 'idx_email', name: 'idx_email', columns: ['email'], unique: false }],
  foreignKeys: [], comment: '', engine: 'InnoDB'
}
const syncTgt = {
  name: 'users',
  columns: [
    col({ name: 'id', originalName: 'id', type: 'int', pk: true, notNull: true }),
    col({ name: 'name', originalName: 'name', type: 'varchar', length: '64', notNull: true }),
    col({ name: 'legacy_col', originalName: 'legacy_col', type: 'text' })
  ],
  indexes: [], foreignKeys: [], comment: '', engine: 'InnoDB'
}
const aligned = ddl.alignDesignForSync(syncSrc, syncTgt)
const syncStmts = ddl.generateAlterTable('mysql', 'mydb', { name: 'users', design: syncTgt }, aligned)
check('同步: 修改差异列', syncStmts, 'MODIFY `name` varchar(128) NOT NULL')
check('同步: 新增源独有列', syncStmts, 'ADD COLUMN `email` varchar(255)')
check('同步: 删除目标多余列', syncStmts, 'DROP COLUMN `legacy_col`')
check('同步: 新增源独有索引', syncStmts, 'ADD INDEX `idx_email` (`email`)')

// 两端一致时不产生语句
const noopSync = ddl.generateAlterTable('mysql', 'mydb', { name: 'users', design: syncTgt },
  ddl.alignDesignForSync(structuredClone(syncTgt), syncTgt))
if (noopSync.filter((s) => !s.startsWith('--')).length === 0) console.log('✓ 同步: 一致时无语句')
else { failures++; console.error(`✗ 同步: 一致时无语句 — 实际: ${noopSync.join(';')}`) }

if (failures > 0) {
  console.error(`\n${failures} 个用例失败`)
  process.exit(1)
}
console.log('\n全部通过')
